#include <stdio.h>
#include <stdlib.h>
#include "board.h"

struct AiMoveVariables {
    int factor;
    int moveCount;
    int board;
    int newMove;
    int row;
    int column;
    int currentMove[2];
    int player;
};


struct Player {
    char playerType;
    int playerNumber;
    int currentMove[2];
    struct AiMoveVariables aiVariables;
};

/*
updates a players current move in the Player struct to the current next move
generated by the ai algorithm to be saved to a file
*/
int next_computer_move(struct Player* p, struct Board* b) {
    int nextMove = p->aiVariables.moveCount % 5;
    switch(nextMove) {
        case 0:
            p->aiVariables.newMove = (p->aiVariables.board + 
                    p->aiVariables.moveCount / 5 * p->aiVariables.factor) %
                    1000003;
            p->currentMove[0] = p->aiVariables.newMove / b->columns;
            p->currentMove[1] = p->aiVariables.newMove % b->columns;
            break;
        case 1:
            p->currentMove[0] = p->aiVariables.row + 1;
            p->currentMove[1] = p->aiVariables.column + 1;
            break;
        case 2:
            p->currentMove[0] = p->aiVariables.row + 2;
            p->currentMove[1] = p->aiVariables.column + 1;
            break;
        case 3:
            p->currentMove[0] = p->aiVariables.row + 1;
            p->currentMove[1] = p->aiVariables.column;
            break;
        case 4:
            p->currentMove[0] = p->aiVariables.row;
            p->currentMove[1] = p->aiVariables.column + 1;
            break;
    }
    return 0;
}

/*
generates the next computer move based on the ai algorithm and increases
the ai move count by 1
*/
int computer_move(struct AiMoveVariables* aiVariables, struct Board* b) {
    int nextMove = aiVariables->moveCount % 5;
    if(aiVariables->moveCount == 0) {
        aiVariables->row = aiVariables->currentMove[0];
        aiVariables->column = aiVariables->currentMove[1];
        aiVariables->moveCount += 1;
        return 0;
    }
    switch(nextMove) {
        case 0:
            aiVariables->newMove = (aiVariables->board + 
                    aiVariables->moveCount / 5 * aiVariables->factor) %
                    1000003;
            aiVariables->row = aiVariables->newMove / b->columns;
            aiVariables->column = aiVariables->newMove % b->columns;
            break;
        case 1:
            aiVariables->row = aiVariables->row + 1;
            aiVariables->column = aiVariables->column + 1;
            break;
        case 2:
            aiVariables->row = aiVariables->row + 2;
            aiVariables->column = aiVariables->column + 1;
            break;
        case 3:
            aiVariables->row = aiVariables->row + 1;
            break;
        case 4:
            aiVariables->column = aiVariables->column + 1;
            break;
    }
    aiVariables->currentMove[0] = aiVariables->row % b->rows;
    aiVariables->currentMove[1] = aiVariables->column % b->columns;
    aiVariables->moveCount += 1;
    return 0;
}

/*
initalizes the variables for the ai move generator based on player number and 
sets the first move
*/
int setup_computer_move_gen(struct AiMoveVariables* aiVariables, 
        struct Board* b, int player) {
    int initialRow, initialColumn;
    if (player == 0) {
        initialRow = 1;
        initialColumn = 4;
        aiVariables->factor = 29;
    }
    if(player == 1) {
        initialRow = 2;
        initialColumn = 10;
        aiVariables->factor = 17;
    }
    aiVariables->moveCount = 0;
    aiVariables->board = initialRow * b->columns + initialColumn;
    aiVariables->row = initialRow;
    aiVariables->column = initialColumn;
    aiVariables->currentMove[0] = aiVariables->row % b->rows;
    aiVariables->currentMove[1] = aiVariables->column % b->columns;
    return 0;
}

/*
attempts to take either the player move or a move generated by te ai algorithm
and place it on the board. If the space is occupied it returns a non zero
value
*/
int make_move(struct Board* b, struct Player* p) {
    if(p->playerType == 'c') {
        p->currentMove[0] = p->aiVariables.currentMove[0];
        p->currentMove[1] = p->aiVariables.currentMove[1];
    }
    if(!is_occupied(b, p->currentMove)) {
        place_stone(b, p->currentMove, p->playerNumber);
        return 1;
    }
    return 0;
}

/*
initalize all the variables for a player and sets up the ai move generator 
(even if they are not a computer player) so that save game is successful
*/
int setup_player(struct Player* p, struct Board* b, char playerType, 
        int playerNumber) {
    p->playerType = playerType;
    p->playerNumber = playerNumber;
    setup_computer_move_gen(&p->aiVariables, b, playerNumber);
    return 0;
}
